#!/usr/bin/env python3
"""Convert a 16 kHz mono WAV generated by Open JTalk into C PCM data."""

import argparse
import struct
import wave
from pathlib import Path


def c_samples(data: bytes, columns: int = 12) -> str:
    samples = struct.unpack(f"<{len(data) // 2}h", data)
    lines = []
    for offset in range(0, len(samples), columns):
        chunk = samples[offset:offset + columns]
        lines.append("    " + ", ".join(str(value) for value in chunk) + ",")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--wav", type=Path, required=True)
    parser.add_argument("--source", type=Path, required=True)
    parser.add_argument("--header", type=Path, required=True)
    parser.add_argument("--symbol", default="g_tts_test_pcm")
    args = parser.parse_args()

    with wave.open(str(args.wav), "rb") as wav:
        sample_rate = wav.getframerate()
        if wav.getnchannels() != 1 or wav.getsampwidth() != 2:
            raise RuntimeError("WAV must be 16-bit mono")
        if sample_rate != 16000:
            raise RuntimeError(f"WAV must be 16 kHz, got {sample_rate} Hz")
        pcm = wav.readframes(wav.getnframes())

    args.source.parent.mkdir(parents=True, exist_ok=True)
    args.header.parent.mkdir(parents=True, exist_ok=True)
    guard = args.header.name.upper().replace(".", "_").replace("-", "_")
    args.header.write_text(
        f"#ifndef {guard}\n#define {guard}\n\n#include <stddef.h>\n#include <stdint.h>\n\n"
        f"extern const int16_t {args.symbol}[];\n"
        f"extern const size_t {args.symbol}_sample_count;\n\n#endif\n",
        encoding="utf-8",
    )
    args.source.write_text(
        f'#include "{args.header.name}"\n\n'
        f"const int16_t {args.symbol}[] __attribute__((aligned(4))) = {{\n"
        f"{c_samples(pcm)}\n}};\n\n"
        f"const size_t {args.symbol}_sample_count = sizeof({args.symbol}) / sizeof({args.symbol}[0]);\n",
        encoding="utf-8",
    )
    print(f"generated {len(pcm) // 2} samples at 16000 Hz")


if __name__ == "__main__":
    main()
